//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoMoClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUserOperate")]
    public interface IUserOperate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserOperate/UserLogin", ReplyAction="http://tempuri.org/IUserOperate/UserLoginResponse")]
        bool UserLogin(string _username, string _pwd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserOperateChannel : MoMoClient.ServiceReference1.IUserOperate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserOperateClient : System.ServiceModel.ClientBase<MoMoClient.ServiceReference1.IUserOperate>, MoMoClient.ServiceReference1.IUserOperate {
        
        public UserOperateClient() {
        }
        
        public UserOperateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserOperateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserOperateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserOperateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UserLogin(string _username, string _pwd) {
            return base.Channel.UserLogin(_username, _pwd);
        }
    }
}
